### ISSUE TITLE
Push Docker images to Zenodo

### ISSUE THREAD

**Issue by yogyagamage** [chains-project/bump#133]

**Comment by frankreyesgarcia** [comment]
All breaking updates in Bump are stored within Docker images. They can be downloaded from [`Zenodo`](https://zenodo.org/records/10041883).
<br>To easily download the Zenodo tar file and load the associated Docker images use the following commands:
<br> ⚠️ **Warning:** You need a minimum of 250 GB of free disk space to load the images.
