### ISSUE TITLE
change categorization of Werror

### ISSUE THREAD

**Issue by monperrus** [chains-project/bump#173]
8 JSON files where category should be Werror.

Plus document the new category in the README 

`<failsOnWarning>true<failsOnWarning>`

**Comment by monperrus** [comment]
did https://github.com/chains-project/bump/pull/174

@frankreyesgarcia will do the other 7 and merge

**Comment by monperrus** [comment]
@frankreyesgarcia if this done, please close the issue with a link to the corresponding commit, thanks!

**Comment by frankreyesgarcia** [comment]
Fixed https://github.com/chains-project/bump/commit/e0ebcf192d1da68b6a6de783951eef22c90919d7

**Comment by monperrus** [comment]
thanks!
