### ISSUE TITLE
Improve handling of tests requiring an API token

### ISSUE THREAD

**Issue by gabrielskoglund** [chains-project/bump#3]
At the moment, the [`GitHubMinerTestBase` class](src/test/java/miner/GitHubMinerTestBase.java), which is used as a base for tests requiring GitHub access is hard coded to look for a file containing a GitHub API token, which means that anyone wanting to run the tests need to supply their own token, and this is not documented.

We should see if we could run the tests without requiring a token, or else set up some better way for the user to provide their own token.

**Comment by gabrielskoglund** [comment]
On second thought, why do we need to make GH requests during testing at all? Should we set up mocks instead?

**Comment by gabrielskoglund** [comment]
For the moment, this has been changed to take an environment variable `TEST_TOKEN` instead. This is fine for use with a GH Action workflow, but is still not great for users running it locally.

**Comment by frankreyesgarcia** [comment]
Low priority
